version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - DATABASE_CONNECTIONSTRING=mongodb://globalhitss_teste:globalhitss_teste@mongodb:27017/teste_globalhitss?authSource=admin
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=globalhitss_teste
      - MONGO_INITDB_ROOT_PASSWORD=globalhitss_teste
      - MONGO_INITDB_DATABASE=teste_globalhitss
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
